# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-org-policy
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Google Cloud Organization Policy v2 Terraform Module
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-org-policy.git
    sourceType: git
  version: 5.3.0
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  examples:
  - name: basic_org_policies
    location: examples/basic_org_policies
  - name: boolean_org_exclude
    location: examples/boolean_org_exclude
  - name: boolean_project_allow
    location: examples/boolean_project_allow
  - name: list_folder_deny
    location: examples/list_folder_deny
  - name: list_org_exclude
    location: examples/list_org_exclude
  - name: v2_boolean_org_enforce
    location: examples/v2_boolean_org_enforce
  variables:
  - name: constraint
    description: The constraint to be applied
    type: string
    required: true
  - name: exclude_folders
    description: Set of folders to exclude from the policy
    type: set(string)
    default: []
    required: false
  - name: exclude_projects
    description: Set of projects to exclude from the policy
    type: set(string)
    default: []
    required: false
  - name: policy_root
    description: 'Resource hierarchy node to apply the policy to: can be one of `organization`, `folder`, or `project`.'
    type: string
    default: organization
    required: false
  - name: policy_root_id
    description: The policy root id, either of organization_id, folder_id or project_id
    type: string
    required: false
  - name: policy_type
    description: The constraint type to work with (either 'boolean' or 'list')
    type: string
    default: list
    required: false
  - name: rules
    description: List of rules per policy. Upto 10.
    type: list(any)
    required: true
  outputs:
  - name: constraint
    description: Policy Constraint Identifier without constraints/ prefix
  - name: policy_root
    description: Policy Root in the hierarchy for the given policy
  - name: policy_root_id
    description: Project Root ID at which the policy is applied
  roles:
  - level: Project
    roles:
    - roles/owner
  - level: Project
    roles:
    - roles/orgpolicy.policyAdmin
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - orgpolicy.googleapis.com
